### ISSUE TITLE
Place for great ideas

### ISSUE THREAD

**Issue by Codeinator-0711** [Team-Earth-Quake-Detector/team_1_earth_quake_detector#13]
- for each task a card in projects
- Protocols for Meetings --> split protocol in single tasks for the project

**Comment by aliciamarleen** [comment]
Hey guys, let's collect helpful links in this chat :)

**Comment by aliciamarleen** [comment]
https://earthquake.usgs.gov/earthquakes/map/?extent=16.21467,-137.19727&extent=55.42901,-52.82227

**Comment by aliciamarleen** [comment]
https://github.com/fraolm/EarthQuakeDetector/blob/master/EarthquickScanner.R

**Comment by karinahasler** [comment]
More inspiration on visualisation issues:

https://openlayers.org/en/latest/examples/heatmap-earthquakes.html

**Comment by karinahasler** [comment]
Implement earthquake effect when refreshing the page? #onlygoodvibes
