### ISSUE TITLE
Understand geo data calcuations

### ISSUE THREAD

**Issue by Codeinator-0711** [Team-Earth-Quake-Detector/team_1_earth_quake_detector#16]
How can we calculate and use geo data?

**Comment by karinahasler** [comment]
Hey coding people,

I found some interesting documentations on the USGS websites on real-time analysis of earthquake data:

https://earthquake.usgs.gov/fdsnws/event/1/

https://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php

I'll check that out!

**Comment by karinahasler** [comment]
Good news: The API is working! After having some troubles with longitude and latitude values (I should really revise some highschool geography stuff!), I found my mistake. In the current version, data on all earthquakes from the last 24 hours with a magnitude > 2.5 is automatically downloaded. However, these parameters can easily be changed.
Looking forward to our next meeting!
