### ISSUE TITLE
Create template from folium output

### ISSUE THREAD

**Issue by karinahasler** [Team-Earth-Quake-Detector/team_1_earth_quake_detector#33]
Folium creates an html file containing the map and the earthquakes:

[https://github.com/Team-Earth-Quake-Detector/team_1_earth_quake_detector/blob/main/use_case/templates/my_map.html](url)

We need to extract the relevant information from the html file to create a custom html file containing our logo, some descriptions and the input fields to be displayed on our web server.

The final output should look approximately like this:

![PHOTO-2021-06-03-15-04-38](https://user-images.githubusercontent.com/83064981/124281255-d48c6b80-db49-11eb-8fb0-ef727a413cdc.jpg)

We have tried using Beautiful Soup to extract the earthquake map HTML code. However, as a result we get only a text that cannot be interpreted as HTML Code anymore.

Also, as fas as we understand it, you can only have dynamic content in the HTML script in the format of plain text, images, hyperlinks etc. and not HTML code including tags etc.

**Comment by aliciamarleen** [comment]
Hallo Herr Zeutschler, soeben konnten wir das Problem selbst lösen, allerdings haben wir nun nicht beautiful soup genutzt. Es besteht hier also kein weiterer Support Bedarf von Ihnen für dieses Problem!
