### ISSUE TITLE
Brainstorm our use-case

### ISSUE THREAD

**Issue by Codeinator-0711** [Team-Earth-Quake-Detector/team_1_earth_quake_detector#8]
Hello conding-people,
we need to meet up and talk about our use case. 

 **Suggestion:** 
- get the same level of knowledge about our repository and the use of it
- work through our use case 
- brainstorm ideas
- sets goals for our use case

**Comment by aliciamarleen** [comment]
Potentially relevant classes:

- **Location** (Default: Current location of computer, refresh functionality, search option) 
- **Map** (Screen filling, selected location in center, zoom in option)
- **Earthquake** (Strength, time stamp, last 24 h)
- **Web Server** (Logo, map, earthquakes overlay)
